import type { ItemInfo } from "../item/[slug]/+page";
import type { PageServerLoad } from "./$types";

export const load: PageServerLoad = ({ url }) => {
    let sortType = url.searchParams.get("sortType") ?? "ASCENDING";
    let sortBy = url.searchParams.get("sortBy") ?? "PRICE_PER_WEIGHT";
    let category = url.searchParams.get("category");
    let query = url.searchParams.get("q");

    console.log({ sortBy, sortType, query });

    return {
        items: [
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
            {
                id: "apple",
                title: "Banana",
                content: "It is a banana",
                img_url: "https://purr.objects-us-east-1.dream.io/i/baby2.jpg",
                price: "$10.00",
                buy_quality: "BAD",
            },
        ] as ItemInfo[],
    };
};
